// Code generated by protoc-gen-gorilla. DO NOT EDIT.

package response_body

import (
	context "context"
	gorilla "github.com/go-leo/gorilla"
	mux "github.com/gorilla/mux"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	http "google.golang.org/genproto/googleapis/rpc/http"
	protojson "google.golang.org/protobuf/encoding/protojson"
	http1 "net/http"
)

type ResponseBodyGorillaService interface {
	OmittedResponse(ctx context.Context, request *Request) (*Response, error)
	StarResponse(ctx context.Context, request *Request) (*Response, error)
	NamedResponse(ctx context.Context, request *Request) (*NamedBodyResponse, error)
	HttpBodyResponse(ctx context.Context, request *Request) (*httpbody.HttpBody, error)
	HttpBodyNamedResponse(ctx context.Context, request *Request) (*NamedHttpBodyResponse, error)
	HttpResponse(ctx context.Context, request *Request) (*http.HttpResponse, error)
}

func AppendResponseBodyGorillaRoute(router *mux.Router, service ResponseBodyGorillaService, opts ...gorilla.Option) *mux.Router {
	options := gorilla.NewOptions(opts...)
	handler := responseBodyGorillaHandler{
		service: service,
		decoder: responseBodyGorillaRequestDecoder{
			unmarshalOptions: options.UnmarshalOptions(),
		},
		encoder: responseBodyGorillaResponseEncoder{
			marshalOptions:      options.MarshalOptions(),
			unmarshalOptions:    options.UnmarshalOptions(),
			responseTransformer: options.ResponseTransformer(),
		},
		errorEncoder: gorilla.DefaultErrorEncoder,
	}
	router.NewRoute().
		Name("/leo.gorilla.example.response_body.v1.ResponseBody/OmittedResponse").
		Methods("GET").
		Path("/v1/omitted/response").
		Handler(handler.OmittedResponse())
	router.NewRoute().
		Name("/leo.gorilla.example.response_body.v1.ResponseBody/StarResponse").
		Methods("GET").
		Path("/v1/star/response").
		Handler(handler.StarResponse())
	router.NewRoute().
		Name("/leo.gorilla.example.response_body.v1.ResponseBody/NamedResponse").
		Methods("GET").
		Path("/v1/named/response").
		Handler(handler.NamedResponse())
	router.NewRoute().
		Name("/leo.gorilla.example.response_body.v1.ResponseBody/HttpBodyResponse").
		Methods("GET").
		Path("/v1/http/body/omitted/response").
		Handler(handler.HttpBodyResponse())
	router.NewRoute().
		Name("/leo.gorilla.example.response_body.v1.ResponseBody/HttpBodyNamedResponse").
		Methods("GET").
		Path("/v1/http/body/named/response").
		Handler(handler.HttpBodyNamedResponse())
	router.NewRoute().
		Name("/leo.gorilla.example.response_body.v1.ResponseBody/HttpResponse").
		Methods("GET").
		Path("/v1/http/response").
		Handler(handler.HttpResponse())
	return router
}

type responseBodyGorillaHandler struct {
	service      ResponseBodyGorillaService
	decoder      responseBodyGorillaRequestDecoder
	encoder      responseBodyGorillaResponseEncoder
	errorEncoder gorilla.ErrorEncoder
}

func (h responseBodyGorillaHandler) OmittedResponse() http1.Handler {
	return http1.HandlerFunc(func(writer http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		in, err := h.decoder.OmittedResponse(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.OmittedResponse(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.OmittedResponse(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h responseBodyGorillaHandler) StarResponse() http1.Handler {
	return http1.HandlerFunc(func(writer http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		in, err := h.decoder.StarResponse(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.StarResponse(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.StarResponse(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h responseBodyGorillaHandler) NamedResponse() http1.Handler {
	return http1.HandlerFunc(func(writer http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		in, err := h.decoder.NamedResponse(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.NamedResponse(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.NamedResponse(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h responseBodyGorillaHandler) HttpBodyResponse() http1.Handler {
	return http1.HandlerFunc(func(writer http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		in, err := h.decoder.HttpBodyResponse(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.HttpBodyResponse(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.HttpBodyResponse(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h responseBodyGorillaHandler) HttpBodyNamedResponse() http1.Handler {
	return http1.HandlerFunc(func(writer http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		in, err := h.decoder.HttpBodyNamedResponse(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.HttpBodyNamedResponse(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.HttpBodyNamedResponse(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h responseBodyGorillaHandler) HttpResponse() http1.Handler {
	return http1.HandlerFunc(func(writer http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		in, err := h.decoder.HttpResponse(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.HttpResponse(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.HttpResponse(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

type responseBodyGorillaRequestDecoder struct {
	unmarshalOptions protojson.UnmarshalOptions
}

func (decoder responseBodyGorillaRequestDecoder) OmittedResponse(ctx context.Context, r *http1.Request) (*Request, error) {
	req := &Request{}
	queries := r.URL.Query()
	var queryErr error
	req.Message = queries.Get("message")
	if queryErr != nil {
		return nil, queryErr
	}
	return req, nil
}
func (decoder responseBodyGorillaRequestDecoder) StarResponse(ctx context.Context, r *http1.Request) (*Request, error) {
	req := &Request{}
	queries := r.URL.Query()
	var queryErr error
	req.Message = queries.Get("message")
	if queryErr != nil {
		return nil, queryErr
	}
	return req, nil
}
func (decoder responseBodyGorillaRequestDecoder) NamedResponse(ctx context.Context, r *http1.Request) (*Request, error) {
	req := &Request{}
	queries := r.URL.Query()
	var queryErr error
	req.Message = queries.Get("message")
	if queryErr != nil {
		return nil, queryErr
	}
	return req, nil
}
func (decoder responseBodyGorillaRequestDecoder) HttpBodyResponse(ctx context.Context, r *http1.Request) (*Request, error) {
	req := &Request{}
	queries := r.URL.Query()
	var queryErr error
	req.Message = queries.Get("message")
	if queryErr != nil {
		return nil, queryErr
	}
	return req, nil
}
func (decoder responseBodyGorillaRequestDecoder) HttpBodyNamedResponse(ctx context.Context, r *http1.Request) (*Request, error) {
	req := &Request{}
	queries := r.URL.Query()
	var queryErr error
	req.Message = queries.Get("message")
	if queryErr != nil {
		return nil, queryErr
	}
	return req, nil
}
func (decoder responseBodyGorillaRequestDecoder) HttpResponse(ctx context.Context, r *http1.Request) (*Request, error) {
	req := &Request{}
	queries := r.URL.Query()
	var queryErr error
	req.Message = queries.Get("message")
	if queryErr != nil {
		return nil, queryErr
	}
	return req, nil
}

type responseBodyGorillaResponseEncoder struct {
	marshalOptions      protojson.MarshalOptions
	unmarshalOptions    protojson.UnmarshalOptions
	responseTransformer gorilla.ResponseTransformer
}

func (encoder responseBodyGorillaResponseEncoder) OmittedResponse(ctx context.Context, w http1.ResponseWriter, resp *Response) error {
	return gorilla.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder responseBodyGorillaResponseEncoder) StarResponse(ctx context.Context, w http1.ResponseWriter, resp *Response) error {
	return gorilla.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder responseBodyGorillaResponseEncoder) NamedResponse(ctx context.Context, w http1.ResponseWriter, resp *NamedBodyResponse) error {
	return gorilla.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp.GetBody()), encoder.marshalOptions)
}
func (encoder responseBodyGorillaResponseEncoder) HttpBodyResponse(ctx context.Context, w http1.ResponseWriter, resp *httpbody.HttpBody) error {
	return gorilla.HttpBodyEncoder(ctx, w, resp)
}
func (encoder responseBodyGorillaResponseEncoder) HttpBodyNamedResponse(ctx context.Context, w http1.ResponseWriter, resp *NamedHttpBodyResponse) error {
	return gorilla.HttpBodyEncoder(ctx, w, resp.GetBody())
}
func (encoder responseBodyGorillaResponseEncoder) HttpResponse(ctx context.Context, w http1.ResponseWriter, resp *http.HttpResponse) error {
	return gorilla.HttpResponseEncoder(ctx, w, resp)
}
