// Code generated by protoc-gen-gors. DO NOT EDIT.

package user

import (
	context "context"
	gorilla "github.com/go-leo/gorilla"
	mux "github.com/gorilla/mux"
	protojson "google.golang.org/protobuf/encoding/protojson"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
)

type UserGorsService interface {
	CreateUser(ctx context.Context, request *CreateUserRequest) (*CreateUserResponse, error)
	DeleteUser(ctx context.Context, request *DeleteUserRequest) (*emptypb.Empty, error)
	ModifyUser(ctx context.Context, request *ModifyUserRequest) (*emptypb.Empty, error)
	GetUser(ctx context.Context, request *GetUserRequest) (*GetUserResponse, error)
	ListUser(ctx context.Context, request *ListUserRequest) (*ListUserResponse, error)
}

func AppendUserGorsRoute(router *mux.Router, service UserGorsService, opts ...gorilla.Option) *mux.Router {
	options := gorilla.NewOptions(opts...)
	handler := userGorsHandler{
		service: service,
		decoder: userGorsRequestDecoder{
			unmarshalOptions: options.UnmarshalOptions(),
		},
		encoder: userGorsResponseEncoder{
			marshalOptions:      options.MarshalOptions(),
			unmarshalOptions:    options.UnmarshalOptions(),
			responseTransformer: options.ResponseTransformer(),
		},
		errorEncoder: gorilla.DefaultErrorEncoder,
	}
	router.NewRoute().
		Name("/leo.gorilla.example.user.v1.User/CreateUser").
		Methods("POST").
		Path("/v1/user").
		Handler(handler.CreateUser())
	router.NewRoute().
		Name("/leo.gorilla.example.user.v1.User/DeleteUser").
		Methods("DELETE").
		Path("/v1/user/{id}").
		Handler(handler.DeleteUser())
	router.NewRoute().
		Name("/leo.gorilla.example.user.v1.User/ModifyUser").
		Methods("PUT").
		Path("/v1/user/{id}").
		Handler(handler.ModifyUser())
	router.NewRoute().
		Name("/leo.gorilla.example.user.v1.User/GetUser").
		Methods("GET").
		Path("/v1/user/{id}").
		Handler(handler.GetUser())
	router.NewRoute().
		Name("/leo.gorilla.example.user.v1.User/ListUser").
		Methods("GET").
		Path("/v1/users").
		Handler(handler.ListUser())
	return router
}

type userGorsHandler struct {
	service      UserGorsService
	decoder      userGorsRequestDecoder
	encoder      userGorsResponseEncoder
	errorEncoder gorilla.ErrorEncoder
}

func (h userGorsHandler) CreateUser() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.CreateUser(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.CreateUser(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.CreateUser(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h userGorsHandler) DeleteUser() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.DeleteUser(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.DeleteUser(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.DeleteUser(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h userGorsHandler) ModifyUser() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.ModifyUser(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.ModifyUser(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.ModifyUser(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h userGorsHandler) GetUser() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.GetUser(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.GetUser(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.GetUser(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h userGorsHandler) ListUser() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.ListUser(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.ListUser(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.ListUser(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

type userGorsRequestDecoder struct {
	unmarshalOptions protojson.UnmarshalOptions
}

func (decoder userGorsRequestDecoder) CreateUser(ctx context.Context, r *http.Request) (*CreateUserRequest, error) {
	req := &CreateUserRequest{}
	if err := gorilla.RequestDecoder(ctx, r, req, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return req, nil
}
func (decoder userGorsRequestDecoder) DeleteUser(ctx context.Context, r *http.Request) (*DeleteUserRequest, error) {
	req := &DeleteUserRequest{}
	vars := gorilla.FormFromMap(mux.Vars(r))
	var varErr error
	req.Id, varErr = gorilla.FormDecoder[int64](varErr, vars, "id", gorilla.GetInt64)
	if varErr != nil {
		return nil, varErr
	}
	return req, nil
}
func (decoder userGorsRequestDecoder) ModifyUser(ctx context.Context, r *http.Request) (*ModifyUserRequest, error) {
	req := &ModifyUserRequest{}
	if err := gorilla.RequestDecoder(ctx, r, req, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	vars := gorilla.FormFromMap(mux.Vars(r))
	var varErr error
	req.Id, varErr = gorilla.FormDecoder[int64](varErr, vars, "id", gorilla.GetInt64)
	if varErr != nil {
		return nil, varErr
	}
	return req, nil
}
func (decoder userGorsRequestDecoder) GetUser(ctx context.Context, r *http.Request) (*GetUserRequest, error) {
	req := &GetUserRequest{}
	vars := gorilla.FormFromMap(mux.Vars(r))
	var varErr error
	req.Id, varErr = gorilla.FormDecoder[int64](varErr, vars, "id", gorilla.GetInt64)
	if varErr != nil {
		return nil, varErr
	}
	return req, nil
}
func (decoder userGorsRequestDecoder) ListUser(ctx context.Context, r *http.Request) (*ListUserRequest, error) {
	req := &ListUserRequest{}
	queries := r.URL.Query()
	var queryErr error
	req.PageNum, queryErr = gorilla.FormDecoder[int64](queryErr, queries, "page_num", gorilla.GetInt64)
	req.PageSize, queryErr = gorilla.FormDecoder[int64](queryErr, queries, "page_size", gorilla.GetInt64)
	if queryErr != nil {
		return nil, queryErr
	}
	return req, nil
}

type userGorsResponseEncoder struct {
	marshalOptions      protojson.MarshalOptions
	unmarshalOptions    protojson.UnmarshalOptions
	responseTransformer gorilla.ResponseTransformer
}

func (encoder userGorsResponseEncoder) CreateUser(ctx context.Context, w http.ResponseWriter, resp *CreateUserResponse) error {
	return gorilla.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder userGorsResponseEncoder) DeleteUser(ctx context.Context, w http.ResponseWriter, resp *emptypb.Empty) error {
	return gorilla.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder userGorsResponseEncoder) ModifyUser(ctx context.Context, w http.ResponseWriter, resp *emptypb.Empty) error {
	return gorilla.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder userGorsResponseEncoder) GetUser(ctx context.Context, w http.ResponseWriter, resp *GetUserResponse) error {
	return gorilla.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder userGorsResponseEncoder) ListUser(ctx context.Context, w http.ResponseWriter, resp *ListUserResponse) error {
	return gorilla.ResponseEncoder(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
