// Code generated by protoc-gen-gorilla. DO NOT EDIT.

package user

import (
	context "context"
	gorilla "github.com/go-leo/gorilla"
	mux "github.com/gorilla/mux"
	protojson "google.golang.org/protobuf/encoding/protojson"
	http "net/http"
)

type UserGorillaService interface {
	CreateUser(ctx context.Context, request *CreateUserRequest) (*CreateUserResponse, error)
	DeleteUser(ctx context.Context, request *DeleteUserRequest) (*DeleteUserResponse, error)
	ModifyUser(ctx context.Context, request *ModifyUserRequest) (*ModifyUserResponse, error)
	UpdateUser(ctx context.Context, request *UpdateUserRequest) (*UpdateUserResponse, error)
	GetUser(ctx context.Context, request *GetUserRequest) (*GetUserResponse, error)
	ListUser(ctx context.Context, request *ListUserRequest) (*ListUserResponse, error)
}

func AppendUserGorillaRoute(router *mux.Router, service UserGorillaService, opts ...gorilla.Option) *mux.Router {
	options := gorilla.NewOptions(opts...)
	handler := userGorillaHandler{
		service: service,
		decoder: userGorillaRequestDecoder{
			unmarshalOptions: options.UnmarshalOptions(),
		},
		encoder: userGorillaResponseEncoder{
			marshalOptions:      options.MarshalOptions(),
			unmarshalOptions:    options.UnmarshalOptions(),
			responseTransformer: options.ResponseTransformer(),
		},
		errorEncoder:            gorilla.DefaultEncodeError,
		shouldFailFast:          options.ShouldFailFast(),
		onValidationErrCallback: options.OnValidationErrCallback(),
	}
	router.NewRoute().
		Name("/leo.gorilla.example.user.v1.User/CreateUser").
		Methods("POST").
		Path("/v1/user").
		Handler(gorilla.Chain(handler.CreateUser(), options.Middlewares()...))
	router.NewRoute().
		Name("/leo.gorilla.example.user.v1.User/DeleteUser").
		Methods("DELETE").
		Path("/v1/user/{id}").
		Handler(gorilla.Chain(handler.DeleteUser(), options.Middlewares()...))
	router.NewRoute().
		Name("/leo.gorilla.example.user.v1.User/ModifyUser").
		Methods("PUT").
		Path("/v1/user/{id}").
		Handler(gorilla.Chain(handler.ModifyUser(), options.Middlewares()...))
	router.NewRoute().
		Name("/leo.gorilla.example.user.v1.User/UpdateUser").
		Methods("PATCH").
		Path("/v1/user/{id}").
		Handler(gorilla.Chain(handler.UpdateUser(), options.Middlewares()...))
	router.NewRoute().
		Name("/leo.gorilla.example.user.v1.User/GetUser").
		Methods("GET").
		Path("/v1/user/{id}").
		Handler(gorilla.Chain(handler.GetUser(), options.Middlewares()...))
	router.NewRoute().
		Name("/leo.gorilla.example.user.v1.User/ListUser").
		Methods("GET").
		Path("/v1/users").
		Handler(gorilla.Chain(handler.ListUser(), options.Middlewares()...))
	return router
}

type userGorillaHandler struct {
	service                 UserGorillaService
	decoder                 userGorillaRequestDecoder
	encoder                 userGorillaResponseEncoder
	errorEncoder            gorilla.ErrorEncoder
	shouldFailFast          bool
	onValidationErrCallback gorilla.OnValidationErrCallback
}

func (h userGorillaHandler) CreateUser() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.CreateUser(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := gorilla.ValidateRequest(ctx, in, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.CreateUser(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.CreateUser(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h userGorillaHandler) DeleteUser() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.DeleteUser(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := gorilla.ValidateRequest(ctx, in, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.DeleteUser(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.DeleteUser(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h userGorillaHandler) ModifyUser() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.ModifyUser(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := gorilla.ValidateRequest(ctx, in, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.ModifyUser(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.ModifyUser(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h userGorillaHandler) UpdateUser() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.UpdateUser(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := gorilla.ValidateRequest(ctx, in, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.UpdateUser(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.UpdateUser(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h userGorillaHandler) GetUser() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.GetUser(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := gorilla.ValidateRequest(ctx, in, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.GetUser(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.GetUser(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

func (h userGorillaHandler) ListUser() http.Handler {
	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		in, err := h.decoder.ListUser(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := gorilla.ValidateRequest(ctx, in, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		out, err := h.service.ListUser(ctx, in)
		if err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
		if err := h.encoder.ListUser(ctx, writer, out); err != nil {
			h.errorEncoder(ctx, err, writer)
			return
		}
	})
}

type userGorillaRequestDecoder struct {
	unmarshalOptions protojson.UnmarshalOptions
}

func (decoder userGorillaRequestDecoder) CreateUser(ctx context.Context, r *http.Request) (*CreateUserRequest, error) {
	req := &CreateUserRequest{}
	ok, err := gorilla.CustomDecodeRequest(ctx, r, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if err := gorilla.DecodeRequest(ctx, r, req, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return req, nil
}
func (decoder userGorillaRequestDecoder) DeleteUser(ctx context.Context, r *http.Request) (*DeleteUserRequest, error) {
	req := &DeleteUserRequest{}
	ok, err := gorilla.CustomDecodeRequest(ctx, r, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	vars := gorilla.FormFromMap(mux.Vars(r))
	var varErr error
	req.Id, varErr = gorilla.DecodeForm[int64](varErr, vars, "id", gorilla.GetInt64)
	req.Id, varErr = gorilla.DecodeForm[int64](varErr, vars, "id", gorilla.GetInt64)
	if varErr != nil {
		return nil, varErr
	}
	return req, nil
}
func (decoder userGorillaRequestDecoder) ModifyUser(ctx context.Context, r *http.Request) (*ModifyUserRequest, error) {
	req := &ModifyUserRequest{}
	ok, err := gorilla.CustomDecodeRequest(ctx, r, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if err := gorilla.DecodeRequest(ctx, r, req, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	vars := gorilla.FormFromMap(mux.Vars(r))
	var varErr error
	req.Id, varErr = gorilla.DecodeForm[int64](varErr, vars, "id", gorilla.GetInt64)
	req.Id, varErr = gorilla.DecodeForm[int64](varErr, vars, "id", gorilla.GetInt64)
	if varErr != nil {
		return nil, varErr
	}
	return req, nil
}
func (decoder userGorillaRequestDecoder) UpdateUser(ctx context.Context, r *http.Request) (*UpdateUserRequest, error) {
	req := &UpdateUserRequest{}
	ok, err := gorilla.CustomDecodeRequest(ctx, r, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if req.Item == nil {
		req.Item = &UserItem{}
	}
	if err := gorilla.DecodeRequest(ctx, r, req.Item, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	vars := gorilla.FormFromMap(mux.Vars(r))
	var varErr error
	req.Id, varErr = gorilla.DecodeForm[int64](varErr, vars, "id", gorilla.GetInt64)
	req.Id, varErr = gorilla.DecodeForm[int64](varErr, vars, "id", gorilla.GetInt64)
	if varErr != nil {
		return nil, varErr
	}
	return req, nil
}
func (decoder userGorillaRequestDecoder) GetUser(ctx context.Context, r *http.Request) (*GetUserRequest, error) {
	req := &GetUserRequest{}
	ok, err := gorilla.CustomDecodeRequest(ctx, r, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	vars := gorilla.FormFromMap(mux.Vars(r))
	var varErr error
	req.Id, varErr = gorilla.DecodeForm[int64](varErr, vars, "id", gorilla.GetInt64)
	req.Id, varErr = gorilla.DecodeForm[int64](varErr, vars, "id", gorilla.GetInt64)
	if varErr != nil {
		return nil, varErr
	}
	return req, nil
}
func (decoder userGorillaRequestDecoder) ListUser(ctx context.Context, r *http.Request) (*ListUserRequest, error) {
	req := &ListUserRequest{}
	ok, err := gorilla.CustomDecodeRequest(ctx, r, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	queries := r.URL.Query()
	var queryErr error
	req.PageNum, queryErr = gorilla.DecodeForm[int64](queryErr, queries, "page_num", gorilla.GetInt64)
	req.PageSize, queryErr = gorilla.DecodeForm[int64](queryErr, queries, "page_size", gorilla.GetInt64)
	if queryErr != nil {
		return nil, queryErr
	}
	return req, nil
}

type userGorillaResponseEncoder struct {
	marshalOptions      protojson.MarshalOptions
	unmarshalOptions    protojson.UnmarshalOptions
	responseTransformer gorilla.ResponseTransformer
}

func (encoder userGorillaResponseEncoder) CreateUser(ctx context.Context, w http.ResponseWriter, resp *CreateUserResponse) error {
	return gorilla.EncodeResponse(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder userGorillaResponseEncoder) DeleteUser(ctx context.Context, w http.ResponseWriter, resp *DeleteUserResponse) error {
	return gorilla.EncodeResponse(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder userGorillaResponseEncoder) ModifyUser(ctx context.Context, w http.ResponseWriter, resp *ModifyUserResponse) error {
	return gorilla.EncodeResponse(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder userGorillaResponseEncoder) UpdateUser(ctx context.Context, w http.ResponseWriter, resp *UpdateUserResponse) error {
	return gorilla.EncodeResponse(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder userGorillaResponseEncoder) GetUser(ctx context.Context, w http.ResponseWriter, resp *GetUserResponse) error {
	return gorilla.EncodeResponse(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
func (encoder userGorillaResponseEncoder) ListUser(ctx context.Context, w http.ResponseWriter, resp *ListUserResponse) error {
	return gorilla.EncodeResponse(ctx, w, encoder.responseTransformer(ctx, resp), encoder.marshalOptions)
}
